package types

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/url"

	"github.com/olekukonko/tablewriter"
	"github.com/pkg/errors"
)

const (
	RecordListURI = "axis-cgi/record/list.cgi"
	EventID       = "ACC_Motion2"
)

/////////////////////////////////////////////////////////////////
//Code generated by chidley https://github.com/gnewton/chidley //
/////////////////////////////////////////////////////////////////

type Recording struct {
	XMLName         xml.Name `xml:"recording,omitempty" json:"recording,omitempty"`
	DiskID          string   `xml:"diskid,attr"  json:",omitempty"`
	EventID         string   `xml:"eventid,attr"  json:",omitempty"`
	EventTrigger    string   `xml:"eventtrigger,attr"  json:",omitempty"`
	Locked          string   `xml:"locked,attr"  json:",omitempty"`
	RecordingID     string   `xml:"recordingid,attr"  json:",omitempty"`
	RecordingStatus string   `xml:"recordingstatus,attr"  json:",omitempty"`
	RecordingType   string   `xml:"recordingtype,attr"  json:",omitempty"`
	Source          string   `xml:"source,attr"  json:",omitempty"`
	StartTime       string   `xml:"starttime,attr"  json:",omitempty"`
	StartTimeLocal  string   `xml:"starttimelocal,attr"  json:",omitempty"`
	StopTime        string   `xml:"stoptime,attr"  json:",omitempty"`
	StopTimeLocal   string   `xml:"stoptimelocal,attr"  json:",omitempty"`
	Video           *Video   `xml:"video,omitempty" json:"video,omitempty"`
}

type Recordings struct {
	XMLName                 xml.Name     `xml:"recordings,omitempty" json:"recordings,omitempty"`
	NumberOfRecordings      string       `xml:"numberofrecordings,attr"  json:",omitempty"`
	TotalNumberOfRecordings string       `xml:"totalnumberofrecordings,attr"  json:",omitempty"`
	Recording               []*Recording `xml:"recording,omitempty" json:"recording,omitempty"`
}

func (recordings *Recordings) String() string {
	output := new(bytes.Buffer)
	table := tablewriter.NewWriter(output)
	table.SetHeader([]string{"ID", "StartTime", "StopTime"})

	var start, stop string
	for _, r := range recordings.Recording {
		start, _ = ToLocalTime(r.StartTime)
		stop, _ = ToLocalTime(r.StopTime)
		table.Append([]string{r.RecordingID, start, stop})
	}
	table.Render()
	return output.String()
}

type RecordingsRoot struct {
	XMLName                           xml.Name    `xml:"root,omitempty" json:"root,omitempty"`
	XsiSpacenoNamespaceSchemaLocation string      `xml:"http://www.w3.org/2001/XMLSchema-instance noNamespaceSchemaLocation,attr"  json:",omitempty"`
	Xmlnsxsi                          string      `xml:"xmlns xsi,attr"  json:",omitempty"`
	Recordings                        *Recordings `xml:"recordings,omitempty" json:"recordings,omitempty"`
}

type Video struct {
	XMLName    xml.Name `xml:"video,omitempty" json:"video,omitempty"`
	FrameRate  string   `xml:"framerate,attr"  json:",omitempty"`
	MimeType   string   `xml:"mimetype,attr"  json:",omitempty"`
	Height     int      `xml:"height,attr"  json:",omitempty"`
	Resolution string   `xml:"resolution,attr"  json:",omitempty"`
	Width      int      `xml:"width,attr"  json:",omitempty"`
}

// getRecordingsList calls the server API and parses the XML response
func GetRecordings(host string) (*Recordings, error) {
	v := url.Values{}
	// v.Set("maxnumberofresults", "20")
	v.Set("recordingid", "all")
	v.Set("eventid", EventID)
	v.Set("sortorder", "descending")
	//v.Set("aftertime", "2018-05-16T15:00:00Z")

	resp, err := http.Get(fmt.Sprintf("http://%s/%s?%s", host, RecordListURI, v.Encode()))
	if err != nil {
		return &Recordings{}, errors.Wrap(err, "HTTP error")
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)

	var root RecordingsRoot
	xml.Unmarshal(body, &root)

	return root.Recordings, nil
}
